### ISSUE TITLE
Season of Docs Discussion

### ISSUE THREAD

**Issue by tharun143** [badging/diversity-and-inclusion#6]
Hello, everyone, this is Tharun Ravuri. I saw this project called Build documentation for D&I Badging project. I want to know more about the work and how to write the documentation. 
BTW is there any separate channel for the discussion of Badging by CHAOSS.

@SMotaal @thecraftman @Nebrethar 

**Mentors: Matt S., Aastha Bist**

They listed they are the mentors. I even tried searching for them in the google groups but couldn't find the group. 

So, that's the reason I opened an issue here. Sorry for this.

**Comment by Nebrethar** [comment]
HI @tharun143 😁 I appreciate that you are interested in the Badging Program. I'm glad you opened an issue here, because that helps us know we need to finish OUR documentation for GSoD!

We are working on the submission and review workflow this Summer, Most of the work for our upcoming GSoD session is related to that workflow. We also have some governance repositories that need improvements in documentation. 

We will be posting microtasks soon so applicants may learn more about D&I Badging and its related projects. I will let you know when those are ready.

Lastly, you asked about separate channels so I will put this here:

**To be more involved with the CHAOSS Badging program:**

- Attend the CHAOSS D&I Meeting at 10am US Central, email me at <msnell@unomaha.edu> for a Zoom invite
- Join the CHAOSS Mailing List found [on the website](https://chaoss.community/participate/) and possibly say hello!
- Open more issues with relevant topics. We always appreciate the feedback

**Comment by Nebrethar** [comment]
Hi again @tharun143 and I hope you are having a great day. I have good news!

I am sending this to let you know that our [microtasks are available](https://github.com/badging/meta/issues/25) for Season of Docs

Thank you!

**Comment by tharun143** [comment]
Thank you @Nebrethar Looking forward to working with you.
