### ISSUE TITLE
Tag D&I Badges  and Metrics with a release year information

### ISSUE THREAD

**Issue by JackieBinya** [badging/diversity-and-inclusion#7]
## `Description`
The best practices criteria and badge of  the [ Core Infrastructure Initiative (CII) Best Practices Badge Program](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/criteria.md) (CII) are both tagged with a release year and from the information in the docs the CII criteria and badges are phased out in every two years at most.

The CII docs also give notice about continuous updates of the best practices criteria and as well as the badges. 
Whereas not much information is available about the D&I badge or metrics in that regard.

## `How do we solve the problem`
My recommendations are that we:
* Determine if the Diversity and Inclusion(D&I) metrics and the badges will be continuously updated.
* If they are updated continuously we then specify the duration of the validity period of both the metrics and badges.
* Tag the D&I Badges  and metrics with release year information.

**Comment by gaurivn** [comment]
Is this issue available, if yes I would like to work on it

**Comment by Nebrethar** [comment]
@JackieBinya This sounds to me like a continuous release schedule! That is a great idea.

Releases & validity has been a discussion on the project but it has become stale over time. I will reopen the conversation and post major results on this issue.

@gaurivn has showed interest in contributing here so I will include you in the discussion.

**Comment by ElizabethN** [comment]
Update on this issue! We have landed on a bi-yearly schedule for DEI Badging releases. They happen a few weeks after the CHAOSS metrics releases (October & April). Because we have 2 per year, we landed on versioning the metrics badge, so a badge is tied to a particular version. Right now we are just badging events, so the badge itself is only good for the duration of that particular event. Organizers will need to re-apply for a new badge each year. 

I'm going to close this issue for now, since it seems to be resolved. Feel free to re-open if discussion should continue. Thanks!
